version: '3.8'

services:
  backend:
    build: ./
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      amorgakco-dev:
    restart: always
    tty: true
    environment:
      SPRING_PROFILES_ACTIVE: dev

  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: amorgakco
      TZ: Asia/Seoul
    volumes:
      - ./docker/mysql/:/var/lib/mysql
    restart: always
    networks:
      amorgakco-dev:
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      amorgakco-dev:
    restart: always
    tty: true

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
      amorgakco-dev:

networks:
  amorgakco-dev:

