version: '3.8'

services:
  backend:
    build: ./
    container_name: backend
    ports:
      - "8080:8080"
      - "9010:9010"
    networks:
      amorgakco-dev:
    restart: always
    tty: true
    environment:
      SPRING_PROFILES_ACTIVE: dev

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: amorgakco
      TZ: Asia/Seoul
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      amorgakco-dev:
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      amorgakco-dev:
    restart: always
    tty: true

volumes:
  mysql_data:
networks:
  amorgakco-dev:

