version: '3.8'

services:
  backend:
    build: ./
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      amorgakco-dev:
    restart: always
    tty: true
    environment:
      SPRING_PROFILES_ACTIVE: dev-gcp
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      amorgakco-dev:
    restart: always
    tty: true

networks:
  amorgakco-dev:

