FROM gradle:7.5.1-jdk17

WORKDIR /app
COPY . /app

ENV JAVA_OPTS="-Dcom.sun.management.jmxremote=true \
               -Dcom.sun.management.jmxremote.local.only=false \
               -Dcom.sun.management.jmxremote.port=9010 \
               -Dcom.sun.management.jmxremote.ssl=false \
               -Dcom.sun.management.jmxremote.authenticate=false \
               -Djava.rmi.server.hostname=34.64.170.190 \
               -Dcom.sun.management.jmxremote.rmi.port=9010"

CMD ["gradle", "bootRun", "-Dorg.gradle.jvmargs=$JAVA_OPTS"]