spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/amorgakco
    hikari:
      username: admin
      password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

fcm-secret-path: fcm-secret.json
